# Generated by Django 4.0 on 2021-12-10 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('date', models.DateTimeField(auto_created=True, auto_now=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('content', models.TextField()),
                ('poster', models.CharField(max_length=20)),
                ('likes', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
