# Generated by Django 4.0 on 2021-12-12 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='cid',
            field=models.IntegerField(default=1),
        ),
    ]
