# Generated by Django 4.0 on 2021-12-12 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_comments_cid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='cid',
            field=models.IntegerField(),
        ),
    ]
